
package com.hidglobal.managedservices.mobileaccess;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.hidglobal.version.GetVersionRequestType;
import com.hidglobal.version.GetVersionResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MobileAccessPortType", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.hidglobal.managedservices.mobileaccess.ObjectFactory.class,
    com.hidglobal.version.ObjectFactory.class,
    com.hidglobal.base.ObjectFactory.class
})
public interface MobileAccessPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.hidglobal.version.GetVersionResponseType
     * @throws FaultMessage
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/getVersion")
    @WebResult(name = "GetVersionResponse", targetNamespace = "http://hidglobal.com/version/", partName = "parameters")
    public GetVersionResponseType getVersion(
        @WebParam(name = "GetVersionRequest", targetNamespace = "http://hidglobal.com/version/", partName = "parameters")
        GetVersionRequestType parameters)
        throws FaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.hidglobal.managedservices.mobileaccess.CreateInvitationResponseType
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/createInvitation")
    @WebResult(name = "CreateInvitationResponse", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
    public CreateInvitationResponseType createInvitation(
        @WebParam(name = "CreateInvitationRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        CreateInvitationRequestType parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/cancelInvitation")
    @Oneway
    public void cancelInvitation(
        @WebParam(name = "CancelInvitationRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        CancelInvitationRequestType parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/deleteDevice")
    @Oneway
    public void deleteDevice(
        @WebParam(name = "DeleteDeviceRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        DeleteDeviceRequestType parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/issueCredential")
    @Oneway
    public void issueCredential(
        @WebParam(name = "IssueCredentialRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        IssueCredentialRequestType parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/revokeCredential")
    @Oneway
    public void revokeCredential(
        @WebParam(name = "RevokeCredentialRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        RevokeCredentialRequestType parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/updateCredential")
    @Oneway
    public void updateCredential(
        @WebParam(name = "UpdateCredentialRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        UpdateCredentialRequestType parameters);

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://managedservices.hidglobal.com/mobileaccess/initiateOrderProcessing")
    @Oneway
    public void initiateOrderProcessing(
        @WebParam(name = "OrderProcessingRequest", targetNamespace = "http://managedservices.hidglobal.com/mobileaccess/", partName = "parameters")
        OrderProcessingRequestType parameters);

}
